pipeline {
    agent any

    tools {nodejs "nodejs"}

    environment{
        CI = 'true'
    }
     
    stages{
        stage('Build') {
            steps {
                echo 'Shuchita'
            }
        
        }

    }
}